spring:
  redis:
    cluster:
      nodes: ${spring.redis.cluster.nodes}
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 400
        max-idle: 150
        max-wait: 1000ms
        min-idle: 0
        shutdown-timeout: 100ms
        maxWaitMillis: 1000
        testOnBorrow: true
        testOnReturn: true
        timeBetweenEvictionRunsMillis: 1000
        numTestsPerEvictionRun: 10
        minEvictableIdleTimeMillis: 300000
  datasource:
    druid:
      filters: stat,slf4j
      maxActive: 30
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000 #60s
      minEvictableIdleTimeMillis: 40000
      maxEvictableIdleTimeMillis: 50000000
      timeBetweenConnectErrorMillis: 30000
      keepAlive: true
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      defaultAutoCommit: true
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 900
      logAbandoned: true
      driver-class-name: com.mysql.jdbc.Driver
      validationQuery: SELECT 'x'
      filter:
        stat:
          logSlowSql: true
          slowSqlMillis: 2000
          mergeSql: true
          enabled: true
        slf4j:
          dataSourceLogEnabled: true
          connectionLogEnabled: true
          statementLogEnabled: true
          resultSetLogEnabled: false
          statementExecutableSqlLogEnable: true
          enabled: true
redis:
  pool:
    maxActive: 200
    maxIdle: 30
    maxWait: 1000
    testOnBorrow: true
    testOnReturn: true
    timeBetweenEvictionRunsMillis: 1000
    numTestsPerEvictionRun: 10
    minEvictableIdleTimeMillis: 300000


restTemplateConnectTimeout: 10000
restTemplateReadTimeout: 10000

# 分页大小
sync.batch.size: 500
commom.query.cache.sign: true

current:
  subsystem: basic-components
